<a href="https://colab.research.google.com/github/bankurucharan/NUMPY-/blob/main/Charan_Bankuru.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Getting Familiar with NumPy : ***

NumPy is a foundational packagein Python,
1. Importing NumPy :-
First, we need to import the NumPy library. It is typically imported with "np":

In [ ]:
import numpy as np

2. **Creating Arrays** :

Arrays are the data structure in NumPy. You can create arrays from Python lists or tuples:

In [2]:
import numpy as np
# 1D Array
array_1d = np.array([1, 2, 3, 4, 5])
# 2D Array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("1D Array:", array_1d)
print("2D Array:\n", array_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


**3. Array Properties:-**

we can easily inspect the properties of NumPy arrays:

In [3]:
import numpy as np
# Shape of the array
print("Shape:", array_2d.shape)
# Size of the array (total number of elements)
print("Size:", array_2d.size)
# Data type of the elements
print("Data Type:", array_2d.dtype)

Shape: (2, 3)
Size: 6
Data Type: int64


**4. Basic Operations:-**

NumPy allows you to perform operations easily:

In [4]:
import numpy as np
#  addition
array_add = array_1d + 10
print("addition:", array_add)
#  multiplication
array_mul = array_1d * 2
print("multiplication:", array_mul)
# square
array_square = np.square(array_1d)
print("square:", array_square)

Element-wise addition: [11 12 13 14 15]
Element-wise multiplication: [ 2  4  6  8 10]
Element-wise square: [ 1  4  9 16 25]


 **Data Manipulation with NumPy :-**

Python program that demonstrates data manipulation using NumPy, focusing on array creation, indexing, slicing, reshaping, and applying mathematical operations.
Array Creation: We create a 1D and a 2D array to work with. The 1D array is a simple vector, and the 2D array is a matrix.

Indexing and Slicing:

We access a single element from the 2D array.
We slice a specific row, column, and sub-array from the 2D array.
Reshaping Arrays:

We reshape the 1D array into a 2D array and flatten a 2D array back into a 1D array.
Mathematical Operations:

We perform element-wise addition, multiplication, squaring, and square root operations on the 1D array.
We also demonstrate matrix multiplication, summing elements, calculating the mean of columns, and transposing the 2D array.

In [6]:
import numpy as np
# 1. Array Creation
# Creating a 1D array
array_1d = np.array([10, 20, 30, 40, 50])
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("1D Array:", array_1d)
print("2D Array:\n", array_2d)
# 2. Indexing and Slicing
# Accessing a single element
element = array_2d[1, 2]
print("\nElement at index [1, 2]:", element)
# Slicing a row
row_slice = array_2d[1, :]
print("Sliced row (2nd row):", row_slice)
# Slicing a column
col_slice = array_2d[:, 1]
print("Sliced column (2nd column):", col_slice)
# 3. Reshaping Arrays
# Reshaping 1D array to 2D array
reshaped_array = np.reshape(array_1d, (5, 1))
print("\nReshaped 1D array to 2D array:\n", reshaped_array)
# Reshaping 2D array to 1D array
flattened_array = array_2d.flatten()
print("Flattened 2D array to 1D array:", flattened_array)
# 4. Mathematical Operations
#  addition
added_array = array_1d + 5
print("addition:", added_array)
# multiplication
multiplied_array = array_1d * 2
print("multiplication:", multiplied_array)
# Sum of all elements
sum_elements = np.sum(array_2d)
print("Sum of all elements in 2D array:", sum_elements)

1D Array: [10 20 30 40 50]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Element at index [1, 2]: 6
Sliced row (2nd row): [4 5 6]
Sliced column (2nd column): [2 5 8]

Reshaped 1D array to 2D array:
 [[10]
 [20]
 [30]
 [40]
 [50]]
Flattened 2D array to 1D array: [1 2 3 4 5 6 7 8 9]
addition: [15 25 35 45 55]
multiplication: [ 20  40  60  80 100]
Sum of all elements in 2D array: 45


**Data Aggregation with NumPy :-**

Summary Statistics:
Mean: The average value of the dataset.
Median: The middle value when the data is sorted.
Standard Deviation: Measures the amount of variation or dispersion in the data.
Sum: The total of all the data points.

In [7]:
import numpy as np
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
# 1. Summary Statistics
mean_value = np.mean(data)
median_value = np.median(data)
std_dev = np.std(data)
total_sum = np.sum(data)
print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_dev)
print("Sum:", total_sum)
# 2. Aggregation on a 2D Array
data_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Sum of each column
sum_columns = np.sum(data_2d, axis=0)
print("\nSum of each column:", sum_columns)
# Mean of each row
mean_rows = np.mean(data_2d, axis=1)
print("Mean of each row:", mean_rows)
# Standard deviation across the entire 2D array
std_dev_2d = np.std(data_2d)
print("Standard Deviation of 2D array:", std_dev_2d)
# Maximum and Minimum values in the 2D array
max_value = np.max(data_2d)
min_value = np.min(data_2d)
print("Maximum value in 2D array:", max_value)
print("Minimum value in 2D array:", min_value)

Mean: 55.0
Median: 55.0
Standard Deviation: 28.722813232690143
Sum: 550

Sum of each column: [12 15 18]
Mean of each row: [2. 5. 8.]
Standard Deviation of 2D array: 2.581988897471611
Maximum value in 2D array: 9
Minimum value in 2D array: 1


**Data Analysis with NumPy:-**
Finding Correlations:

We calculate the correlation coefficient between two datasets (data_x and data_y). The correlation coefficient measures the strength and direction of the linear relationship between the two variables.

Calculating Percentiles:

We calculate the 25th, 50th (median), and 75th percentiles of the data. Percentiles help us understand the distribution of data points within the dataset.

In [8]:
import numpy as np
data_x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data_y = np.array([2, 4, 5, 4, 5, 6, 8, 8, 9, 10])
#Correlations
correlation = np.corrcoef(data_x, data_y)[0, 1]
print("Correlation Coefficient between data_x and data_y:", correlation)
# Calculating Percentiles
percentile_25 = np.percentile(data_x, 25)
percentile_50 = np.percentile(data_x, 50)
percentile_75 = np.percentile(data_x, 75)
print("\n25th Percentile of data_x:", percentile_25)
print("50th Percentile of data_x (Median):", percentile_50)
print("75th Percentile of data_x:", percentile_75)

Correlation Coefficient between data_x and data_y: 0.9683205555268893

25th Percentile of data_x: 3.25
50th Percentile of data_x (Median): 5.5
75th Percentile of data_x: 7.75


***Application in Data Science :-***

How NumPy Helps Data Science Professionals

NumPy is a fundamental tool in the toolkit of any data science professional. Here's how NumPy can help:

**Efficient Data Handling:**

Performance: NumPy arrays are optimized for performance. Operations on NumPy arrays are executed much faster than on Python lists due to the use of low-level optimized C libraries. This speed is crucial when dealing with large datasets, common in data science tasks.

**Integration with Other Data Science Tools:**
NumPy seamlessly integrates with other essential data science libraries, such as Pandas for data manipulation, Matplotlib for data visualization, and Scikit-Learn for machine learning.

Real-World Examples Where NumPy’s Capabilities Are Crucial
Machine Learning:

Linear Algebra Operations: Many machine learning algorithms, such as linear regression and neural networks, rely heavily on linear algebra operations like matrix multiplication, which are efficiently handled by NumPy.
Data Preprocessing: Data preprocessing tasks like normalization, standardization, and feature scaling are commonly performed using NumPy arrays. The ability to handle large datasets quickly is crucial in training machine learning models.
Financial Analysis:

Time Series Analysis: Financial analysts use NumPy for analyzing time series data, such as stock prices, interest rates, and market indices. Operations like calculating moving averages, volatility, and returns are efficiently performed using NumPy.

**Conclusion**:-

NumPy is a powerful library that forms the backbone of numerical computation in Python, particularly in the field of data science. we explored its core functionalities, from creating arrays and performing basic operations to manipulating, aggregating, and analyzing data efficiently. NumPy’s ability to handle large datasets with speed and precision, its extensive mathematical and statistical functions, and its seamless integration with other data science libraries make it an indispensable tool for professionals in the field.

In summary, NumPy’s capabilities enable data scientists to handle a wide range of computational tasks with ease, making it a foundational library that underpins much of the work done in data-driven fields today.